[package]
name = "discord_todo"
version = "0.1.0"
authors = ["luc mayor"]
edition = "2021"

[dependencies]
chrono = "0.4.39"
regex = "1.11.1"
serenity = "0.12.4"
tokio = {version = "1.43.0", features = ["full"]}
